version: '3'

services:
  source_db:
    image: postgres:15
    container_name: source_postgres
    environment:
      POSTGRES_DB: source_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: hajiku1234soa
    ports:
      - "5432:5432"
    volumes:
      - ./data:/docker-entrypoint-initdb.d

  destination_db:
    image: postgres:15
    container_name: destination_postgres
    environment:
      POSTGRES_DB: target
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: hajiku1234soa
    ports:
      - "5433:5432"
